webapp:
 build: webapp
 ports:
  - "8080:8080"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

player:
 build: player/player-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 links:
  - couchdb
 ports:
  - "9443:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

concierge:
 build: concierge/concierge-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 links:
  - player
 ports:
  - "9081:9080"
  - "9444:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

map:
 build: map/map-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 links:
  - couchdb
 ports:
  - "9447:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

couchdb:
 image: klaemo/couchdb:latest
 expose:
  - "5984"

mediator:
 build: mediator/mediator-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 ports:
  - "9086:9086"
  - "9446:9446"
 links:
  - concierge
  - room
  - player
 env_file: gameon.${DOCKER_MACHINE_NAME}env

room:
 build: room/room-wlpcfg
 links:
  - concierge
 ports:
  - "9080:9080"
  - "9445:9445"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

proxy:
 build: proxy
 env_file: gameon.${DOCKER_MACHINE_NAME}env
 links:
  - webapp
  - player
  - concierge
  - room
  - map
  - mediator
 ports:
  - "80:80"
  - "443:443"
  - "1936:1936"
