auth:
 build: auth/auth-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 external_links:
  - kafka
  - registry
  - logstash
  - controller
 ports:
  - "9089:9080"
  - "9449:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

player:
 build: player/player-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 external_links:
  - couchdb
  - kafka
  - registry
  - logstash
  - controller
 ports:
  - "4201:4201"
  - "9082:9080"
  - "9443:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

map:
 build: map/map-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 external_links:
  - couchdb
  - kafka
  - registry
  - logstash
  - controller
 ports:
  - "9099:9080"
  - "9447:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

mediator:
 build: mediator/mediator-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 ports:
  - "9086:9080"
  - "9446:9443"
 links:
  - room
 external_links:
  - kafka
  - registry
  - logstash
  - controller
 env_file: gameon.${DOCKER_MACHINE_NAME}env

proxy:
 build: proxy
 env_file: gameon.${DOCKER_MACHINE_NAME}env
 links:
  - webapp
  - room
 external_links:
  - kafka
  - registry
  - logstash
  - controller
 ports:
  - "80:80"
  - "443:443"
  - "1936:1936"

webapp:
 build: webapp
 # image: gameontext/gameon-webapp
 ports:
  - "8080:8080"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

room:
 build: room/room-wlpcfg
 links:
  - map
 external_links:
  - kafka
 ports:
  - "9080:9080"
  - "9445:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env
