webapp:
 build: webapp
 ports:
  - "8080:8080"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

player:
 build: player/player-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 links:
  - couchdb
 ports:
  - "9082:9080"
  - "9443:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

map:
 build: map/map-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 links:
  - couchdb
  - player
 ports:
  - "9099:9080"
  - "9447:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

couchdb:
 image: klaemo/couchdb:latest
 expose:
  - "5984"

mediator:
 build: mediator/mediator-wlpcfg
 volumes:
  - './keystore:/opt/ibm/wlp/usr/servers/defaultServer/resources/security'
 ports:
  - "9086:9080"
  - "9446:9443"
 links:
  - room
  - player
  - map
 env_file: gameon.${DOCKER_MACHINE_NAME}env

room:
 build: room/room-wlpcfg
 links:
  - map
 ports:
  - "9080:9080"
  - "9445:9443"
 env_file: gameon.${DOCKER_MACHINE_NAME}env

proxy:
 build: proxy
 env_file: gameon.${DOCKER_MACHINE_NAME}env
 links:
  - webapp
  - player
  - room
  - map
  - mediator
 ports:
  - "80:80"
  - "443:443"
  - "1936:1936"

zookeeper:
 container_name: zookeeper
 image: "wurstmeister/zookeeper"
 ports:
   - "2181:2181"

kafka:
 container_name: kafka
 image: "cantireinnovations/kafka:0.9.0.0"
 environment:
  KAFKA_BROKER_ID: 1
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 1000
 ports:
  - "9092:9092"
  - "7080:7080"
 links:
 - "zookeeper:zookeeper"
